server:
  port: 8888
  contextPath: /test
  # tomcat设置
  tomcat:
    accesslog:
    # 开启日志访问
      enabled: true
    # 日志保存路径
      directory: D:/logs
      
  
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.model
  check-config-location: true
  
logging:
  level:
    com:
      example:
        dao: debug
        
spring: 
    datasource: 
      url: jdbc:mysql://192.168.145.160:3306/bxptest1?useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
